# Generated by Django 4.1.3 on 2022-11-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocollection',
            old_name='photo',
            new_name='file',
        ),
    ]
